### ISSUE TITLE
Reduce cpu time for "find" operation

### ISSUE THREAD

**Issue by schoolie** [schoolie3344/ScreepsCoop#1]
If you look at my creeps, most of them are running a "find" on every tick, which is expensive. We should make them use memory instead to find a target and store its ID only when switching from "not working" to "working" state or vice versa. Then they can move toward it until they can work/harvest and clear the target. If you start poking around, that would be a cool thing to work on.

**Comment by schoolie3344** [comment]
This has been partially solved. Most "working" tasks now use a "target" in memory. Sources are still being 'found' each tick. They need to be set as "creep.memory.target" in the not working state, and the script should be modified for this to function.

**Comment by schoolie** [comment]
This is solved now, right? if so, go ahead and close it. Reference a PR or commit that fixed it if possible.

**Comment by schoolie3344** [comment]
Oh, and the sources are still being found every tick as well, I just packed the old logic into a function to make things cleaner and more modifiable

**Comment by schoolie3344** [comment]
Made a further improvement to this, finally allowing sources to be stored in memory instead of being found every tick. At this point, I am pretty sure finds are only being run when target is null and a new target needs to be found. Closing issue.

commit cc29cf9993f7532f0a5ac81d7f47a1d2508fcac2

**Comment by schoolie3344** [comment]
The first issue ever is finally closed ;)

**Comment by schoolie** [comment]
and there was much rejoicing!
