### ISSUE TITLE
extensionConstruction

### ISSUE THREAD

**Issue by schoolie3344** [schoolie3344/ScreepsCoop#15]
Extension construction is currently not functional. I had an old system that worked, but was very expensive. I modified it to use memory and decrease CPU cost, but something got bugged. Mine will be very hard to understand even with comments, so a new method may be the best option. We need to do a periodic check (Maybe a Game.time % x == 0 check in main) to see if extensions are available to be constructed. If so, create a procedural method to place them near the spawn, or near the source by the spawn. Near the spawn may decrease traffic issues, near source could reduce time spent commuting.

**Comment by schoolie** [comment]
solved with #34, closing
