### ISSUE TITLE
Can't link to repo from desktop app...

### ISSUE THREAD

**Issue by schoolie** [schoolie3344/ScreepsCoop#16]
I tried setting up the desktop app under my old screeps account (schoolie54, I'm spawned at W1S53, figured it wouldn't hurt to have two colonies to play with). When trying to link my account to our repo, the dialog box just shakes like there's an error.

I found this, which suggests it might be a filetype problem. I'm wondering if the docs folder is messing us up. 

I'd suggest restructuring the repo to have a structure something like this to see if it helps:

/
    docs/
        ....
    ai_code/
        main.js
        construct.extensions.js
        ....
    ....

Then when we setup sync from github, we can nav to ai_code/ and hopefully avoid this problem?

**Comment by schoolie3344** [comment]
It may just be that screeps doesn't allow multiple accounts linked to the
same repository. Try cloning it to another account or something and linking
there. If it works we know what it is.

**Comment by schoolie** [comment]
Yep, looks like that was it. I forked to schoolie/ScreepsCoop and it worked fine.
