### ISSUE TITLE
Error generated in repair logic

### ISSUE THREAD

**Issue by schoolie** [schoolie3344/ScreepsCoop#30]
I've gotten this error a few times via email:

```
jobs:140
      if(repairTarget.hits == repairTarget.hitsMax) {
                      ^

TypeError: Cannot read property 'hits' of null
    at Object.repairStructures (jobs:140:23)
    at Object.run (workerManager:44:14)
    at Object.module.exports.loop (main:13:19)
    at __mainLoop:1:52
    at sigintHandlersWrap (vm.js:98:15)
```

Looks like occasionally there aren't any structures that need repair, and that's throwing an error?

**Comment by schoolie3344** [comment]
Yeah, sorry so have I. Haven't really tried to track it down yet. I am
assuming I just need to move that into an existing if(target) or add a new
one. I assume that runs after something gets completely repaired and target
goes null or something.

**Comment by schoolie** [comment]
No big deal, just wanted to add it to the issues list so it doesn't get lost :)

**Comment by schoolie3344** [comment]
I may have just fixed it. We'll give it a few days and see if any errors
come up

**Comment by schoolie3344** [comment]
Haven't seen any new errors, so closing issue
