### ISSUE TITLE
First creep spawns with class 'army'

### ISSUE THREAD

**Issue by schoolie** [schoolie3344/ScreepsCoop#33]
After respawn, the first creep pops out and does nothing. He has the body of a worker [WORK, CARRY, MOVE], but his class assignment is 'army.'

**Comment by schoolie3344** [comment]
Just a mistype somehow. fixed

**Comment by schoolie** [comment]
Fixed with commit: 47101e0ad7d7663dad030caaf05fcfd1aea972fa
