### ISSUE TITLE
I broke the spawning

### ISSUE THREAD

**Issue by schoolie3344** [schoolie3344/ScreepsCoop#41]
The recovery spawning script broke spawning and 3 body part creeps are being spawned...

**Comment by schoolie** [comment]
Just confirming that I noticed this in my colony as well. Forgot to create the issue though, and haven't attempted to debug yet.

**Comment by schoolie3344** [comment]
I fixed it. Thanks for the response ;)
I had done one of my common mistakes: 
I had a for(creep in creeps) loop and I referenced something as creep.body instead of creeps[creep].body.

**Comment by schoolie** [comment]
fixed with https://github.com/schoolie3344/ScreepsCoop/commit/7bb3a3a66a0924568c9de82a88e1491ad6425e2d
