### ISSUE TITLE
Room Capture!

### ISSUE THREAD

**Issue by schoolie3344** [schoolie3344/ScreepsCoop#6]
We just hit GCL 2, and it would be great to capture a room. In the past, I kinda brute forced this with a lot of variable manipulation and console control, and a little bit of automation. It would be great if we could make our first room capture this time happen autonomously just so we know we can.

**Comment by schoolie** [comment]
Not sure how much you've done to investigate this, but these two roles were what I was working on to get this working:

https://github.com/schoolie/screeps_ai/blob/master/role.observer.js
https://github.com/schoolie/screeps_ai/blob/master/role.claimer.js

Here's how I think I was trying to structure the logic:

role.observer.shouldSpawn compares the number of spawns in the game with the GCL, and starts spawning 'observers' if they don't match.

The observer's only job is to go sit in the middle of the next room we want to claim (currently hardcoded as 7, but there could easily be logic applied there). I remember having trouble figuring out how to get "visibility" into a room, so this was my way around that. 

After the observer is spawned, I then spawn the 'claimer.'  His job is to go to the same room as the observer and 'claim' the controller.

It's very likely possible to combine the two roles, but I seem to remember the claimer is expensive and slow, and I got sick of losing them on the way to the new room, or something like that.

Once the room is claimed, both roles become builders, which reverts to upgraders when there's nothing to build.

I had also begun (finished?) structuring my spawn logic to be room independent, so as soon as a new spawn is claimed, it just starts pumping out creeps according to the rules defined for the other room.

**Comment by schoolie** [comment]
Also, this is a place where we should really get a private server running for testing. Want to set that up again?

**Comment by schoolie3344** [comment]
I'll take a look at the code. I'm sure I can steal some. Did you look into
the "observer" structure at all?

**Comment by schoolie** [comment]
Yeah, the observer structure makes things a lot easier, but you don't get it until RCL 8 I think?

**Comment by thebestschoolie** [comment]
in case either of you wanted to use vim, I placed a screeps.vim syntax file in the /docs folder of our repo. On linux, copy it to  ~/.vim/syntax/screeps.vim. You may have to create the .vim/syntax dirs. Then make a file in ~/.vim/ftdetect called screeps-detect.vim. In that file write this line of code and save:

`au BufRead,BufNewFile *.js set filetype=screeps`

**Comment by schoolie3344** [comment]
Nice. I'm doing well with atom currently, but I will probably do some vim
learning once I am rolling well. Have you gotten to look at any code yet?

**Comment by schoolie3344** [comment]
I have a decent roomCapture setup now, that we shouldn't need to improve for a while outside of possible bug fixes
