### ISSUE TITLE
Get Vim Keyword highlighting working

### ISSUE THREAD

**Issue by thebestschoolie** [schoolie3344/ScreepsCoop#9]
in case either of you wanted to use vim, I placed a screeps.vim syntax file in the /docs folder of our repo. On linux, copy it to ~/.vim/syntax/screeps.vim. You may have to create the .vim/syntax dirs. Then make a file in ~/.vim/ftdetect called screeps-detect.vim. In that file write this line of code and save:

`au BufRead,BufNewFile *.js set filetype=screeps`

**Comment by schoolie3344** [comment]
Closing since we have a solution
